from nanovllm_voxcpm.llm import VoxCPM

try:
    from nanovllm_voxcpm._version import version as __version__
except Exception:
    # `_version.py` is generated by setuptools_scm during packaging.
    __version__ = "2.0.3"

__all__ = [
    "VoxCPM",
    "__version__",
]
